name: json_patch
description: Pure Dart utility package for the JSON Patch standard. Can apply patch operations as well as perform a diff algorithm on JSON-like objects.
version: 2.1.1
homepage: https://github.com/pikaju/dart-json-patch

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  collection: ^1.15.0

dev_dependencies:
  test: ^1.17.5
